CREATE TABLE IF NOT EXISTS public.directories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    alias character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT directories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.email_actions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    subject character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT email_actions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ig_followers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    account_name character varying COLLATE pg_catalog."default" NOT NULL,
    created_on date NOT NULL,
    CONSTRAINT ig_followers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ig_following (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    account_name character varying COLLATE pg_catalog."default" NOT NULL,
    created_on date NOT NULL,
    CONSTRAINT ig_following_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ig_nmf (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    account_name character varying COLLATE pg_catalog."default" NOT NULL,
    created_on date NOT NULL,
    protected boolean NOT NULL DEFAULT false,
    CONSTRAINT ig_nmf_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    username VARCHAR(64) NOT NULL
);
